#!/usr/bin/env node
// rebar MCP server — this repository's rules, served from the generated artifact.
//
// WHY IT EXISTS, in the owner's words: "No Herz e no BMB Compras eu não tive esse
// problema porque elaborei um MCP com todas as regras de projeto, pra ele sempre
// ficar na memória e forçar a ser usadas." [On Herz and on BMB Compras I did not have
// this problem because I built an MCP with all the project rules, so it would always
// stay in memory and force them to be used.] And the defect that was left over: "O
// MCP não era reescrito quando as regras de projeto foram modificadas." [The MCP was
// not rewritten when the project rules were modified.]
//
// The fix is in two pieces, and ONLY ONE of them lives here:
//
//   mcp/generate.mjs           derives mcp/rules.generated.json from the source, and the `mcp`
//                           step of `npm run verify` regenerates it in memory and
//                           FAILS if the disk diverges. That is the freshness gate.
//   mcp/src/*  (this)       serves the artifact. Never reads tooling/rebar-check/index.mjs.
//
// WHAT THIS SERVER IS NOT — §7.2, literal: "O MCP nunca é a porta. A porta é N0–N5."
// [The MCP is never the door. The door is N0–N5.] Calling a tool from here is a
// shortcut against getting it wrong; what fails you is `npm run verify`, the hook and
// the CI. No answer below authorizes anything.
//
// WHAT CHANGED FROM THE PREVIOUS VERSION OF THIS FILE. It served PROSE: five tools
// returning chunks of docs/PLANO.md by section. That contradicts §7.2 for two
// measured reasons — prose is the format Herz proved ignorable (17 guides, 1,961
// lines, 80 KB, "o modelo decide se chama" [the model decides whether to call it]),
// and the plan is what the project INTENDS while the artifact is what the gate FAILS
// today. When the two diverge, whoever fails you is in charge. The prose stays
// reachable: the tools return `file:line` from the PLANO instead of copying the text
// over here.

import { execFile } from 'node:child_process'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { promisify } from 'node:util'

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'

import {
  avisoDeFrescor,
  carregar,
  CAMINHO_ARTEFATO,
  exibirCaminho,
  FalhaDeArtefato,
  frescor,
  RAIZ,
} from './artefato.mjs'
import { catalogo, decidir, portao, porque } from './consultas.mjs'

const executar = promisify(execFile)

// ─────────────────────────────────────────────────────────────────────────────
// Boot: die loud if the artifact does not exist.
//
// An MCP server that comes up without its data source answers "no rule found" to
// everything, and the model concludes the project has no rules. An empty answer with
// the face of an answer is worse than a dead server: a dead server the owner fixes
// today.
// ─────────────────────────────────────────────────────────────────────────────
try {
  carregar()
} catch (e) {
  if (e instanceof FalhaDeArtefato) {
    console.error(`rebar-mcp: ${e.message}`)
    process.exit(1)
  }
  throw e
}

const texto = (t) => ({ content: [{ type: 'text', text: t }] })
const erro = (t) => ({ content: [{ type: 'text', text: t }], isError: true })

/**
 * Reloads the artifact ON EVERY CALL and glues the freshness warning to the answer.
 *
 * No cache, on purpose: the whole module exists because a stale copy went on being
 * served with nobody noticing. If `node mcp/generate.mjs` runs while this session is
 * open, the next call already answers with the new rule. Measured cost: 79 KB of
 * JSON, ~1 ms.
 */
function comArtefato(fn) {
  return async (args) => {
    let artefato
    try {
      artefato = carregar()
    } catch (e) {
      return erro(`rebar-mcp: ${e.message}`)
    }
    const aviso = avisoDeFrescor(frescor(artefato))
    const corpo = await fn(artefato, args ?? {})
    const conteudo = typeof corpo === 'string' ? texto(corpo) : corpo
    if (!aviso) return conteudo
    return {
      ...conteudo,
      content: [{ type: 'text', text: aviso }, ...conteudo.content],
    }
  }
}

const servidor = new McpServer({ name: 'rebar', version: '0.2.0' })

// ─── 1. the catalog ──────────────────────────────────────────────────────────
servidor.registerTool(
  'rebar_regras',
  {
    title: 'The rules that fail this repository',
    description:
      'Lists the rebar-check rules, grouped by level N0–N7, with id, class and title. ' +
      'CALL IT BEFORE WRITING CODE in this repository or in a project generated by it: it is the ' +
      'list of what will fail at the commit and in the CI. Filter by level, class or term so it ' +
      'does not bring everything. Derived from mcp/rules.generated.json; the reason behind each ' +
      'rule comes out of rebar_porque.',
    inputSchema: {
      nivel: z.string().optional().describe('N0..N7 — only the rules at that level'),
      classe: z
        .string()
        .optional()
        // The two class values stay in Portuguese: they are what the artifact stores.
        .describe('determinística (fails) or heurística (only warns); a prefix is enough'),
      busca: z.string().optional().describe('term in the id or the title; unaccented works'),
    },
  },
  comArtefato((artefato, args) => catalogo(artefato, args)),
)

// ─── 2. the why ──────────────────────────────────────────────────────────────
servidor.registerTool(
  'rebar_porque',
  {
    title: 'Why this rule exists, with the measured number',
    description:
      'Returns the reason behind a rule (or a closed decision) by id: the why paragraphs read ' +
      'from the source with file:line, and the proof cases that lock it. ' +
      'CALL IT WHEN THE GATE FAILS and you are tempted to work around the rule, and BEFORE ' +
      'proposing to loosen, ignore or delete any check. Almost every reason here brings the ' +
      'number that measured it; a measured number is not negotiable.',
    inputSchema: {
      id: z.string().describe('id of the rule, e.g. "hex-cru", or of a closed decision'),
    },
  },
  comArtefato((artefato, { id }) => {
    const r = porque(artefato, id)
    return r.ok ? texto(r.texto) : erro(r.texto)
  }),
)

// ─── 3. what has already been decided ────────────────────────────────────────
servidor.registerTool(
  'rebar_decidir',
  {
    title: 'What this project has already decided about X',
    description:
      'Searches a subject in the artifact and answers what rebar has already decided about it: a ' +
      'closed decision with the file:line that proves it, a rule that enforces it, or a gate step. ' +
      'CALL IT BEFORE PROPOSING any choice of stack, library, format or process — the decision ' +
      'probably already exists and is proved in code. When nothing matches, it SAYS that nothing ' +
      'enforces that, instead of inventing: that is an answer too.',
    inputSchema: {
      // The example subjects stay in Portuguese: they are queries against the
      // artifact's own text, which is Portuguese.
      assunto: z.string().describe('the subject, in words: "cor", "env", "tailwind", "commit"'),
    },
  },
  comArtefato((artefato, { assunto }) => decidir(artefato, assunto)),
)

// ─── 4. the gate ─────────────────────────────────────────────────────────────
servidor.registerTool(
  'rebar_portao',
  {
    title: 'The gate steps, in order, and what to do when one fails',
    description:
      'Returns the steps of `npm run verify` in order, the command of each one and the exit codes; ' +
      'with { passo } it returns the repair hint for that step. ' +
      'CALL IT WHEN THE VERIFIER FAILS and the message is not enough, and before saying that ' +
      'anything "passed". This MCP is not the door: the door is the command this tool returns.',
    inputSchema: {
      passo: z.string().optional().describe('name or number of the step, e.g. "mcp" or "5"'),
    },
  },
  comArtefato((artefato, { passo }) => portao(artefato, passo)),
)

// ─── 5. run the ruler ────────────────────────────────────────────────────────
//
// The only tool that EXECUTES. It runs the same binary as the hook and the CI
// (`tooling/rebar-check/index.mjs --json`), so there is no second verdict to diverge
// from the first — it is a shortcut to the same command, not a new opinion.
//
// It runs the CHECKER, not the whole `npm run verify`: the 11 steps include the test
// suite and prettier over the whole repository, which is too expensive for a tool
// call and is already the gate's job. Here it answers the quick question "do the 22
// rules pass on this path?" — in ~1 s, measured.
//
// process.execPath and execFile, never `npx` and never a shell: on Windows `npx`
// without shell:true does not exist as an executable, and that is the defect that
// survived in the foundation because the CI only ran Linux.
const CHECKER = join(RAIZ, 'tooling', 'rebar-check', 'index.mjs')

servidor.registerTool(
  'rebar_verificar',
  {
    title: 'Run the ruler on a path and return the scoreboard',
    description:
      'Runs rebar-check (the same one as the hook and the CI) on a path and returns, per rule, ' +
      'what passed, failed or is not applicable, plus the exit code. ' +
      'CALL IT AFTER TOUCHING the repository, and before claiming you are done. ' +
      'A SHORTCUT, NOT A BARRIER: what blocks is `npm run verify` in the hook and in the CI; a ' +
      'green here does not replace the gate, which still runs format, links, secret, proofs and ' +
      'MCP freshness.',
    inputSchema: {
      caminho: z
        .string()
        .optional()
        .describe('folder to audit; it has to be a git repository. Default: the rebar root'),
      regra: z.string().optional().describe('id of a single rule, to iterate fast'),
    },
  },
  comArtefato(async (artefato, { caminho, regra }) => {
    if (!existsSync(CHECKER)) {
      return erro(
        [
          `rebar-mcp: the checker is not in this checkout (expected at ${exibirCaminho(CHECKER)}).`,
          'The other tools keep serving the artifact; only execution depends on the repository.',
        ].join('\n'),
      )
    }
    if (regra && !artefato.regras.some((r) => r.id === regra)) {
      return erro(`"${regra}" is not a rule. See the list in rebar_regras.`)
    }

    const alvo = caminho?.trim() ? caminho.trim() : RAIZ
    const args = [CHECKER, '--json']
    if (regra) args.push(`--rule=${regra}`)
    args.push(alvo)

    let saida
    let codigo = 0
    try {
      saida = await executar(process.execPath, args, {
        cwd: RAIZ,
        timeout: 120_000,
        maxBuffer: 16 * 1024 * 1024,
        windowsHide: true,
      })
    } catch (e) {
      // The checker exits 1 when it fails: that is a result, not a failed call.
      if (typeof e.code !== 'number') {
        return erro(`rebar-mcp: the checker did not run: ${e.message}`)
      }
      codigo = e.code
      saida = e
    }

    const significado = artefato.codigosDeSaida?.[String(codigo)] ?? '(unknown code)'

    let avaliacoes
    try {
      avaliacoes = JSON.parse(saida.stdout)
    } catch {
      return erro(
        [
          `rebar-mcp: exit=${codigo} (${significado}) and the output is not JSON.`,
          (saida.stderr || saida.stdout || '').trim().slice(0, 1500),
        ].join('\n'),
      )
    }

    const blocos = avaliacoes.map((a) => {
      if (a.erro) return `${a.nome}: ${a.erro}`
      // 'reprovou', 'quebrou', 'na' and 'heurística' below stay in Portuguese: they
      // are the values rebar-check --json writes, not prose. Translated, every filter
      // here comes back empty and the scoreboard reads all-green over a red run.
      const reprovou = a.resultados.filter((x) => x.estado === 'reprovou')
      const quebrou = a.resultados.filter((x) => x.estado === 'quebrou')
      const na = a.resultados.filter((x) => x.estado === 'na')
      // The checker's `nota` counts ONLY the deterministic ones — it is the scoreboard
      // that decides the exit. Heuristics go on a line of their own; otherwise "13/13"
      // next to seven listed n/a does not add up and the reader concludes something
      // vanished.
      const heu = a.resultados.filter((x) => x.classe === 'heurística')
      const heuAvisou = heu.filter((x) => x.estado === 'reprovou').length
      const linhas = [
        `target: ${a.nome}`,
        `deterministic (these fail): ${a.nota.ok}/${a.nota.total} passed · ${a.nota.na} not applicable · ${a.nota.quebrou} broke`,
        `heuristic (only warn): ${heu.length - heuAvisou - heu.filter((x) => x.estado === 'na').length} passed · ${heuAvisou} warned · ${heu.filter((x) => x.estado === 'na').length} not applicable`,
      ]
      if (quebrou.length) {
        linhas.push('', 'BROKE (a rebar-check defect, not a target defect):')
        for (const x of quebrou) linhas.push(`  ${x.id}  ${x.motivo ?? ''}`)
      }
      if (reprovou.length) {
        linhas.push('', 'FAILED:')
        for (const x of reprovou) {
          linhas.push(`  ${x.id} (${x.nivel} ${x.classe})  ${x.motivo ?? ''}`)
        }
        linhas.push(`  → the reason behind each one: rebar_porque { id: "${reprovou[0].id}" }`)
      }
      if (!reprovou.length && !quebrou.length) linhas.push('', 'No rule failed.')
      if (na.length) {
        linhas.push('', `not applicable: ${na.map((x) => x.id).join(', ')}`)
      }
      return linhas.join('\n')
    })

    return [
      `exit=${codigo} — ${significado}`,
      `command: node tooling/rebar-check/index.mjs --json${regra ? ` --rule=${regra}` : ''} ${exibirCaminho(alvo)}`,
      '',
      blocos.join('\n\n'),
      '',
      'This is the ruler, not the gate. The gate is `npm run verify` (rebar_portao shows the steps).',
    ].join('\n')
  }),
)

// The boot log goes to stderr, always: stdout is the JSON-RPC channel, and any loose
// byte in there breaks the client handshake.
console.error(
  `rebar-mcp: 5 tools, artifact at ${exibirCaminho(CAMINHO_ARTEFATO)}, ${carregar().regras.length} rules.`,
)

await servidor.connect(new StdioServerTransport())
